{
 "title": "02 - Fetch and Commit Metrics",
 "description": "Kafka Consumer Java client metrics",
 "tags": [ "consumer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Fetch Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_fetch_total{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", client_id!~\"^.+-restore-consumer$\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average Fetch Size / Request",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_size_avg{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", client_id!~\"^.+-restore-consumer$\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average Fetch Latency",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", client_id!~\"^.+-restore-consumer$\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average Commit Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_latency_avg{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Commit Calls / second",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_coordinator_commit_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}