{
 "title": "03 - Throughput",
 "description": "Kafka Consumer Java client metrics",
 "tags": [ "consumer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_consumer_app_infor_start_time_ms{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Incoming Messages / second (client)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_consumer_fetch_manager_records_consumed_total{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}[$__rate_interval])) by (instance, client_id)",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate (client)",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic=~\".*\", job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}[$__rate_interval])) by (instance, client_id)",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Incoming Messages / second (topic)",
   "type": "timeseries",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_consumer_fetch_manager_records_consumed_total{topic!=\"\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Incoming Byte Rate (topic)",
   "type": "timeseries",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic=~\".+\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}