{
 "title": "05 - Connections",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "consumer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (client_id, instance) (kafka_consumer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"})",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Connection rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(kafka_consumer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Creation Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_connection_creation_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Close Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_consumer_connection_close_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}