{
 "title": "07 - Authentication",
 "description": "Apache Kafka resource usage and throughput",
 "tags": [ "consumer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful Authentication Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (kafka_consumer_successful_authentication_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} ({{client_id}})"
    }
   ]
  },
  {
   "title": "Failed Authentication Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (kafka_consumer_failed_authentication_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} ({{client_id}})"
    }
   ]
  },
  {
   "title": "Successful Authentication Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kafka_consumer_successful_authentication{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} ({{client_id}})"
    }
   ]
  },
  {
   "title": "Failed Authentication Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kafka_consumer_failed_authentication{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} ({{client_id}})"
    }
   ]
  }
 ]
}