{
 "title": "08 - Consumer Lag",
 "description": "Kafka Consumer Java client metrics",
 "tags": [ "consumer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{cluster_type=~\"streams|consumer\", job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_consumer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"},client_id)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_consumer_fetch_manager_records_consumed_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", topic=~\".+\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Lag By Topic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum by(client_id_truncated, topic_truncated) (label_replace(label_replace(kafka_consumer_fetch_manager_records_lag{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", client_id!~\"^.+-restore-consumer$\", topic=~\"${topic}\"}, \"topic_truncated\", \"${1}\", \"topic\", \"(.{0,64})(.*)\"), \"client_id_truncated\", \"${1}\", \"client_id\", \"^(.*?)(-consumer|)$\") > 0)",
     "legendFormat": "{{topic_truncated}} ({{client_id_truncated}})"
    }
   ]
  },
  {
   "title": "Consumer Lag By Partition",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum by(client_id_truncated, topic_truncated, partition) (label_replace(label_replace(kafka_consumer_fetch_manager_records_lag{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", client_id!~\"^.+-restore-consumer$\", topic=~\"${topic}\"}, \"topic_truncated\", \"${1}\", \"topic\", \"(.{0,64})(.*)\"), \"client_id_truncated\", \"${1}\", \"client_id\", \"^(.*?)(-consumer|)$\") > 0)",
     "legendFormat": "{{partition}} - {{topic_truncated}} ({{client_id_truncated}})"
    }
   ]
  },
  {
   "title": "Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "targets": [
    {
     "expr": "sum by (client_id_truncated, topic_truncated) (label_replace(label_replace(kafka_consumer_fetch_manager_records_consumed_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\", client_id!~\"^.+-restore-consumer$\", topic=~\"${topic}\"}, \"topic_truncated\", \"${1}\", \"topic\", \"(.{0,64})(.*)\"), \"client_id_truncated\", \"${1}\", \"client_id\", \"^(.*?)(-consumer$|$)\"))",
     "legendFormat": "{{topic_truncated}} ({{client_id_truncated}})"
    }
   ]
  }
 ]
}