{
 "title": "02 - Kafka Consumer",
 "description": "Kafka Consumer Java client metrics",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_info{cluster_type=~\"streams|producer|consumer\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_consumer_app_info_start_time_ms{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit rate",
   "type": "stat",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Average fetch throttle time",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_throttle_time_avg{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Failed auth rate",
   "type": "stat",
   "description": "Rate of failed authentication attempts\n",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_failed_authentication_rate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "description": "The number of total rebalance events per hour, both successful and unsuccessful rebalance attempts.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_rebalance_rate_per_hour{job=~\"$job\", instance=~\"$instance\"} + kafka_consumer_consumer_coordinator_metrics_failed_rebalance_rate_per_hour{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes consumed rate",
   "type": "timeseries",
   "description": "The average number of bytes consumed per second\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic=~\".*\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed",
   "type": "timeseries",
   "description": "The average number of records consumed per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{topic=~\"$topic\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Bytes consumed rate per topic",
   "type": "timeseries",
   "description": "The average number of bytes consumed per topic per second.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_consumer_consumer_fetch_manager_metrics_bytes_consumed_total{topic!=\"\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Rate of records consumed per topic",
   "type": "timeseries",
   "description": "The average number of records consumed per second per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{topic!=\"\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Fetch Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fetch request rate",
   "type": "timeseries",
   "description": "The number of fetch requests per second.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_consumer_fetch_manager_metrics_fetch_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Fetch size avg",
   "type": "timeseries",
   "description": "The average number of bytes fetched per request for a topic",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Fetch latency average",
   "type": "timeseries",
   "description": "The average time taken for a fetch request.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_fetch_manager_metrics_fetch_latency_avg{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Consumer Commit Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit latency average",
   "type": "timeseries",
   "description": "The average time taken for a commit request",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_latency_avg{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Commit rate",
   "type": "timeseries",
   "description": "The number of commit calls per second .",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_coordinator_metrics_commit_rate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current connection count",
   "type": "timeseries",
   "description": "Number of simultaneous connections\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_metrics_connection_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Node reponse rate",
   "type": "timeseries",
   "description": "response rate per node\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_consumer_node_metrics_response_rate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  }
 ]
}