{
 "title": "98 - Kafka Producer",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "producer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=~\"streams|producers|consumers\"},cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_producer_app_info_start_time_ms{cluster_id=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Key metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Retry rate",
   "type": "stat",
   "description": "The average per-second number of retried record sends for a topic. An increase could signal connectivity problems from the application to the broker. ",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_retry_rate{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Record error rate",
   "type": "stat",
   "description": "The average per-second number of record sends that resulted in errors.\n",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_error_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Free buffer space",
   "type": "stat",
   "description": "he total amount of buffer memory that is not being used (either unallocated or in the free list).",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_buffer_available_bytes{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce request throttle average",
   "type": "stat",
   "description": "The average time in ms a request was throttled by a broker.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_produce_throttle_time_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Compression rate",
   "type": "stat",
   "description": "The average compression rate of record batches for a topic, defined as the average ratio of the compressed batch size over the uncompressed size.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_compression_rate_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Produce request latency",
   "type": "timeseries",
   "description": "The average request latency in ms.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_latency_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}}({{instance}})"
    }
   ]
  },
  {
   "title": "Record queue time",
   "type": "timeseries",
   "description": "The average time in ms record batches spent in the send buffer.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_queue_time_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed authentication rate",
   "type": "timeseries",
   "description": "The rate of failed authentication per seconds\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_failed_authentication_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Outgoing byte rate",
   "type": "timeseries",
   "description": "The average number of bytes sent per second to the broker.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_outgoing_byte_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}}({{instance}})"
    }
   ]
  },
  {
   "title": "Outgoing byte rate per topic",
   "type": "timeseries",
   "description": "The average number of bytes sent per second to the broker per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_byte_total{topic=~\".*\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second",
   "type": "timeseries",
   "description": "The average number of messages sent per second to the broker.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_record_send_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Outgoing messages per second per topic",
   "type": "timeseries",
   "description": "The average number of messages sent per second to the broker per topic.\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_producer_topic_metrics_record_send_total{}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch size average",
   "type": "timeseries",
   "description": "The average number of bytes sent per partition per-request.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg{}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Request in flight",
   "type": "timeseries",
   "description": "The current number of in-flight requests awaiting a response.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_requests_in_flight{}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Record size average",
   "type": "timeseries",
   "description": "The average record size",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_size_avg{}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Produce Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Produce request rate",
   "type": "timeseries",
   "description": "The average number of requests sent per second to the broker.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_request_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Produce request size average",
   "type": "timeseries",
   "description": "The average number of records per request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_size_avg{}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Produce response rate",
   "type": "timeseries",
   "description": "The average number of response received per second to the broker.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_response_total{}[$__rate_interval])",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection rate",
   "type": "timeseries",
   "description": "The current number of active connections.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connection creation rate",
   "type": "timeseries",
   "description": "New connections established per second in the window.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_connection_creation_rate{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Connection close rate",
   "type": "timeseries",
   "description": "Connections closed per second in the window.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_connection_close_rate{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "timeseries",
   "description": "The fraction of time the I/O thread spent doing I/O.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_ratio{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "IO Wait time average",
   "type": "timeseries",
   "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_wait_time_ns_avg{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "IO Time average",
   "type": "timeseries",
   "description": "The average length of time for I/O per select call in nanoseconds.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_time_ns_avg{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "IO Wait Ratio",
   "type": "timeseries",
   "description": "The fraction of time the I/O thread spent waiting.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_io_wait_ratio{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Select Rate",
   "type": "timeseries",
   "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_select_rate{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "API Version",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(kafka_producer_app_info{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\",version!=\"\"}) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "Metadata max age",
     "type": "timeseries",
     "description": "The age in seconds of the current producer metadata being used.",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_producer_producer_metrics_metadata_age{env=\"$env\",client_id=~\"$client_id\",hostname=~\"$hostname\"}",
       "legendFormat": "{{client_id}}@{{hostname}}"
      }
     ]
    }
   ]
  }
 ]
}