{
 "title": "99 - Kafka Producer Performance",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "producer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=~\"streams|producers|consumers\"},cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_producer_app_info_start_time_ms{cluster_id=~\"$cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Batch size average",
   "type": "timeseries",
   "description": "The average number of bytes sent per partition per-request.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_batch_size_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request in flight",
   "type": "timeseries",
   "description": "The current number of in-flight requests awaiting a response.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_requests_in_flight{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Record size average",
   "type": "timeseries",
   "description": "The average record size",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_record_size_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Produce Request metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Produce request rate",
   "type": "timeseries",
   "description": "The average number of requests sent per second to the broker.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_request_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Produce request size average",
   "type": "timeseries",
   "description": "The average number of records per request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "kafka_producer_producer_metrics_request_size_avg{cluster_id=~\"$cluster\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Produce response rate",
   "type": "timeseries",
   "description": "The average number of response received per second to the broker.\n",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_producer_metrics_response_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}