{
 "title": "04 - Connections",
 "description": "Apache Kafka resource usage and throughput",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\", job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Connection Count / Listener",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kafka_server_socket_server_metrics_connection_count{job=~\"$job\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Connection Rate / Listener",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kafka_server_socket_server_metrics_connection_creation_rate{job=~\"$job\", instance=~\"$instance\"}) by (listener)",
     "legendFormat": "{{listener}}"
    }
   ]
  },
  {
   "title": "Client Versions",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_socket_server_metrics_connections{job=~\"$job\",instance=~\"$instance\"} > 0) by (clientSoftwareName, clientSoftwareVersion)",
     "legendFormat": "{{clientSoftwareName}} - {{clientSoftwareVersion}}"
    }
   ]
  }
 ]
}