{
 "title": "06 - Request Metrics (Rate)",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\", job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Metrics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(instance, version) (kafka_network_requestmetrics_oneminuterate{job=~\"$job\", name=\"RequestsPerSec\", instance=~\"$instance\"}) ",
     "legendFormat": "{{request}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance, name) (kafka_network_requestchannel_value{job=~\"$job\", instance=~\"$instance\", processor=\"\"}) ",
     "legendFormat": "{{name}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Request Metrics / Broker",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without(version) (kafka_network_requestmetrics_oneminuterate{job=~\"$job\", name=\"RequestsPerSec\", instance=~\"$instance\"}) ",
     "legendFormat": "{{request}} ({{instance}})"
    }
   ]
  }
 ]
}