{
 "title": "06 - Request Metrics (Latency)",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\"}, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\", job=\"$job\"}, instance)"
    }
   },
   { "name": "percentile", "query": "50,75,95,99,999" }
  ]
 },
 "panels": [
  {
   "title": "Total Time / Broker - Producer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(kafka_network_requestmetrics_${percentile}thpercentile{job=~\"$job\", instance=~\"$instance\",name=\"TotalTimeMs\",request=\"Produce\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Time - Producer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(name) (kafka_network_requestmetrics_${percentile}thpercentile{job=~\"$job\", instance=~\"$instance\",request=\"Produce\", name =~ \".+Ms\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Time / Broker - Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(kafka_network_requestmetrics_${percentile}thpercentile{job=~\"$job\", instance=~\"$instance\",name=\"TotalTimeMs\",request=\"FetchConsumer\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Time - Consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (name) (kafka_network_requestmetrics_${percentile}thpercentile{job=~\"$job\", instance=~\"$instance\",request=\"FetchConsumer\", name =~ \".+Ms\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Time / Broker - Follower",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(kafka_network_requestmetrics_${percentile}thpercentile{job=~\"$job\",instance=~\"$instance\",name=\"TotalTimeMs\",request=\"FetchFollower\",})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Time - Follower",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (name) (kafka_network_requestmetrics_${percentile}thpercentile{job=~\"$job\", instance=~\"$instance\",request=\"FetchFollower\", name =~ \".+Ms\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}