{
 "title": "10 - Topics",
 "tags": [
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(jvm_runtime_info{cluster_type=\"kafka\"}, job)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\",instance=~\".*\",name=\"BytesInPerSec\",topic!~\"__confluent.+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Topic Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kafka_log_log_value{job=~\"$job\", name=\"Size\", topic=~ '$topic'}) by (partition))"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kafka_log_log_value{job=~\"$job\", name=\"Size\", topic='$topic'}) by (partition))"
    }
   ]
  },
  {
   "title": "offset difference",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(kafka_log_log_value{job=~\"$job\", name=\"LogEndOffset\", topic =~ \"$topic\"}) by (partition)) - sum(max(kafka_log_log_value{name=\"LogStartOffset\", topic =~ \"$topic\"}) by (partition))"
    }
   ]
  },
  {
   "title": "Total Messages (of all time)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (max by(partition) (kafka_log_log_value{job=~\"$job\", name=\"LogEndOffset\", topic =~ \"$topic\"}))"
    }
   ]
  },
  {
   "title": "Log Segments",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{job=~\"$job\", name=\"NumLogSegments\", topic=\"$topic\"})"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_log_log_value{job=~\"$job\", name=\"LogEndOffset\", topic =~ \"$topic\"}) - sum (kafka_log_log_value{job=~\"$job\", name=\"LogStartOffset\", topic =~ \"$topic\"})"
    }
   ]
  },
  {
   "title": "messages in / sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\", name=\"MessagesInPerSec\", topic = \"${topic}\"})"
    }
   ]
  },
  {
   "title": "bytes in / sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\", name=\"BytesInPerSec\", topic = \"${topic}\"})"
    }
   ]
  },
  {
   "title": "bytes out / sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\", name=\"BytesOutPerSec\", topic=\"${topic}\"})"
    }
   ]
  },
  {
   "title": "Messages In - ${topic}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\", name=\"MessagesInPerSec\",topic = \"${topic}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In - ${topic}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\", name=\"BytesInPerSec\",topic = \"${topic}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out - ${topic}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{job=~\"$job\", name=\"BytesOutPerSec\",topic = \"${topic}\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "messages in / sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{job=~\"$job\", name=\"MessagesInPerSec\", topic=\"${topic}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "bytes in / sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{job=~\"$job\", name=\"BytesInPerSec\",topic = \"${topic}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "bytes out / sec",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_count{job=~\"$job\", name=\"BytesOutPerSec\",topic = \"${topic}\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Messages In - ${topic}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_count{job=~\"$job\", name=\"MessagesInPerSec\", topic = \"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In - ${topic}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_count{job=~\"$job\", name=\"BytesInPerSec\", topic = \"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out - ${topic}",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_count{job=~\"$job\", name=\"BytesOutPerSec\", topic = \"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}