{
 "title": "12 - Consumer Lag",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "koffset",
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(koffset_latest_offset,job)"
    }
   },
   {
    "name": "topic",
    "query": {
     "query": "label_values(koffset_latest_offset{job=\"$job\"},topic)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(koffset_group_offset{job=\"$job\", topic=~\"$topic\"},group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Groups",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "koffset_number_of_groups{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stable",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (koffset_group_info{state=\"STABLE\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalancing",
   "type": "stat",
   "description": "\n    UNKNOWN(\"Unknown\"),\n    PREPARING_REBALANCE(\"PreparingRebalance\"),\n    COMPLETING_REBALANCE(\"CompletingRebalance\"),\n    STABLE(\"Stable\"),\n    DEAD(\"Dead\"),\n    EMPTY(\"Empty\"),\n    ASSIGNING(\"Assigning\"),\n    RECONCILING(\"Reconciling\"),\n    NOT_READY(\"NotReady\");\n",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (koffset_group_info{state=~\"PREPARING_REBALANCE|COMPLETING_REBALANCE\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Empty",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (koffset_group_info{state=\"EMPTY\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Members",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(koffset_group_members{}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collected @",
   "type": "stat",
   "description": "the time when the consumer group metrics were collected within koffset",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "koffset_refreshed_ts{} * 1000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Data Age",
   "type": "stat",
   "description": "how old the consumer group data from koffset is to the rendered time of the dashboard.",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - (koffset_refreshed_ts{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Refreshed Age",
   "type": "stat",
   "description": "the age of the consumer group data when collected by prometheus",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "koffset_refreshed_age_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Time To Gather Metrics",
   "type": "stat",
   "description": "how long it takes for koffset to capture the consumer group metrics (async withink koffset)",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "koffset_refreshed_duration_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Groups",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "max by (partition,pod,group,state,coordinator) (koffset_group_info{group=~\"$group\", group=~\".+\"})"
      },
      {
       "expr": "max by (partition,pod,group) (koffset_group_members{group=~\"$group\", group=~\".+\"})"
      },
      {
       "expr": "max by (partition,pod,group) (koffset_group_members_assigned{group=~\"$group\", group=~\".+\"})"
      }
     ]
    },
    {
     "title": "Consumer Lag",
     "type": "table",
     "gridPos": { "h": 23, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "max by (topic,partition,pod,group) (koffset_group_offset{topic=~\"$topic\",group=~\"$group\", group=~\".+\"})"
      },
      {
       "expr": "max by (topic,partition,pod,group) (koffset_group_lag{topic=~\"$topic\",group=~\"$group\", group=~\".+\"})"
      },
      {
       "expr": "max by (topic,partition,pod,group) (koffset_group_lag_seconds{topic=~\"$topic\",group=~\"$group\", group=~\".+\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message in per second",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(koffset_latest_offset{job=\"$job\", instance=~\".*\",topic=~\"$topic\"}[1m]) / 60) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Group Velocity",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(koffset_group_velocity_records_per_sec{job=\"$job\", instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}) by (group, topic) ",
       "legendFormat": "{{group}} / {{topic}}"
      }
     ]
    },
    {
     "title": "Message in per minute",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(koffset_latest_offset{job=\"$job\", instance=~'.*', topic=~\"$topic\"}[1m])/1) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Lag by  Consumer Group",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(koffset_group_lag{job=\"$job\", instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}) by (group, topic) ",
       "legendFormat": "{{group}} / {{topic}}"
      }
     ]
    },
    {
     "title": "Message consume per minute",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(delta(koffset_group_offset{job=\"$job\", instance=~'.*',topic=~\"$topic\"}[1m])/1) by (group, topic)",
       "legendFormat": "{{group}} / {{topic}}"
      }
     ]
    },
    {
     "title": "Lag by  Consumer Group",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(koffset_group_lag{job=\"$job\", instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}) by (group, topic, partition) ",
       "legendFormat": "{{group}} / {{topic}}-{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Group Lag In Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag (seconds)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(koffset_group_lag_seconds{job=\"$job\", instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}) by (group, topic) ",
       "legendFormat": "{{group}} / {{topic}}"
      }
     ]
    },
    {
     "title": "Lag (seconds) / Partition",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(koffset_group_lag_seconds{job=\"$job\", instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}) by (group, topic, partition) ",
       "legendFormat": "{{group}} / {{topic}}-{{partition}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Group Lag In Time Per Group Over Offset Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$group",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "repeat": "group",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(koffset_group_lag_seconds{job=~\"$job\",group=~\"$group\"})",
       "legendFormat": "lag (time)"
      },
      {
       "expr": "sum(koffset_group_lag{job=~\"$job\",group=~\"$group\"})",
       "legendFormat": "lag (offset)"
      },
      {
       "expr": "max(  min_over_time(koffset_group_offset_stale_seconds{job=~\"$job\",group=~\"$group\"}[30s]))",
       "legendFormat": "stale (time)"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer Group Lag in Time Per Group Over Summed Offsets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "$group",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 346 },
     "repeat": "group",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(koffset_group_lag_seconds{job=~\"$job\",group=~\"$group\",group!=\"\"}) by (group)",
       "legendFormat": "group lag (time)"
      },
      {
       "expr": "sum(koffset_group_offset{job=~\"$job\",group=~\"$group\",group!=\"\"})",
       "legendFormat": "group (offstes)"
      },
      {
       "expr": "sum((koffset_group_offset{job=~\"$job\",group=~\"$group\",group!=\"\"} * 0)\n+ on(job,topic,partition) group_left() kafka_partition_latest_offset{job=~\"$job\"})",
       "legendFormat": "lastest (offset)"
      }
     ]
    }
   ]
  }
 ]
}