{
 "title": "13 - Consumer Lag (compare)",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "koffset",
  "kafka_cluster",
  "kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": {
     "query": "label_values(koffset_latest_offset,topic)"
    }
   },
   {
    "name": "partition",
    "query": {
     "query": "label_values(koffset_latest_offset{topic=~\"$topic\"},partition)"
    }
   },
   {
    "name": "group",
    "query": {
     "query": "label_values(koffset_group_offset{topic=~\"$topic\"},group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Lag (offsets)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lag (offsets)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(koffset_group_lag{instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}[30s])) by (group, topic) ",
     "legendFormat": "koffset - {{group}} / {{topic}}"
    },
    {
     "expr": "sum(avg_over_time(kafka_consumergroup_group_lag{instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}[30s])) by (group, topic) ",
     "legendFormat": "kle - {{group}} / {{topic}}"
    }
   ]
  },
  { "title": "Lag (seconds)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Lag (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(avg_over_time(koffset_group_lag_seconds{instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}[30s])) by (group, topic) ",
     "legendFormat": "koffset - {{group}} / {{topic}}"
    },
    {
     "expr": "max(avg_over_time(kafka_consumergroup_group_lag_seconds{instance=~\".*\",topic=~\"$topic\", group=~\"$group\"}[30s])) by (group, topic) ",
     "legendFormat": "kle - {{group}} / {{topic}}"
    }
   ]
  },
  {
   "title": "Lag (seconds) / Partition",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Lag (seconds) / Partition",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(koffset_group_lag_seconds{topic=~\"$topic\", group=~\"$group\", partition=~\"$partition\"}) by (group, topic, partition) ",
       "legendFormat": "{{group}} / {{topic}}-{{partition}}"
      },
      {
       "expr": "max(kafka_consumergroup_group_lag_seconds{topic=~\"$topic\", group=~\"$group\", partition=~\"$partition\"}) by (group, topic, partition) ",
       "legendFormat": "{{group}} / {{topic}}-{{partition}}"
      }
     ]
    }
   ]
  }
 ]
}