{
 "title": "02 - Streams - Tasks",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\", cluster_id=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_streams_stream_thread_metrics_task_created_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_rate{cluster_id=~\"$cluster\", instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_rate{instance=~\"${instance}\",thread_id=~\"${thread}\"}, partition_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Subtopology (Task) Description",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "application_streams{cluster_type=\"streams\", cluster_id=~\"$cluster\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "process latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(task, partition_id, thread_id, instance) (kafka_streams_stream_task_metrics_process_latency_avg{partition_id=~\"${partition}\",task_id=~\"${task}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})/1000000",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process latency (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(partition_id, task_id, thread_id, instance, cluster_id, job, cluster_type) (kafka_streams_stream_task_metrics_process_latency_avg{partition_id=~\"${partition}\", task_id=~\"${task}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})/1000000",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(task, partition_id, thread_id, instance) (kafka_streams_stream_task_metrics_process_rate{partition_id=~\"${partition}\",task_id=~\"${task}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(partition_id, task_id, thread_id, instance, cluster_id, job, cluster_type) (kafka_streams_stream_task_metrics_process_rate{partition_id=~\"${partition}\", task_id=~\"${task}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(task, partition_id, thread_id, instance)  (kafka_streams_stream_task_metrics_process_total{partition_id=~\"${partition}\",task_id=~\"${task}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(partition_id, task_id, thread_id, instance, cluster_id, cluster_type, job) (kafka_streams_stream_task_metrics_process_total{partition_id=~\"${partition}\", task_id=~\"${task}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "record lateness (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(task, partition_id, thread_id, instance)  (kafka_streams_stream_task_metrics_record_lateness_avg{partition_id=~\"${partition}\",task_id=~\"${task}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "record lateness (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(partition_id, task_id, thread_id, instance, cluster_id, job) (kafka_streams_stream_task_metrics_record_lateness_avg{partition_id=~\"${partition}\", task_id=~\"${task}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "records dropped total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(task, partition_id, thread_id, instance)  (kafka_streams_stream_task_metrics_dropped_records_total{partition_id=~\"${partition}\",task_id=~\"${task}\",thread_id=~\"${thread}\",instance=~\"${instance}\",cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{cluster_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "records dropped total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(partition_id, task_id, thread_id, instance, cluster_id, job, cluster_type) (kafka_streams_stream_task_metrics_dropped_records_total{partition_id=~\"${partition}\", task_id=~\"${task}\", thread_id=~\"${thread}\",instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}