{
 "title": "03 - Topics",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\"}, job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_client_state{job=~\"${job}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"${job}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_stream_topic_bytes_consumed_total{job=~\"$job\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_stream_topic_bytes_consumed_total{instance=~\"${instance}\", thread_id=~\"${thread}\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "total messages consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (kafka_stream_topic_records_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\", processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"})",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "total bytes consumed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_stream_topic_bytes_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"})",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "total messages produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_stream_topic_records_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"})",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "total bytes produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_stream_topic_bytes_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"})",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "messages consumed (rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (rate(kafka_stream_topic_records_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\", processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "bytes consumed (rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(kafka_stream_topic_bytes_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "messages produced (rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(kafka_stream_topic_records_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "bytes produced (rate)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  (rate(kafka_stream_topic_bytes_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "messages consumed (rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(topic, processor_node_id) (rate(kafka_stream_topic_records_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\", processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "messages produced (rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(topic, processor_node_id) (rate(kafka_stream_topic_records_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "bytes consumed (rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic, processor_node_id) (rate(kafka_stream_topic_bytes_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  },
  {
   "title": "bytes produced (rate)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(topic, processor_node_id) (rate(kafka_stream_topic_bytes_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
     "legendFormat": "{{topic}} ({{processor_node_id}})"
    }
   ]
  }
 ]
}