{
 "title": "04 - Tasks",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"$source\"},job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_client_state{job=~\"${job}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"${job}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_stream_thread_process_rate{job=~\"$job\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(kafka_stream_task_process_rate{job=~\"$job\", instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values(kafka_stream_task_process_rate{instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum without(thread_id, instance)  (kafka_stream_task_process_total{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",job=~\"${job}\"} + on (job, instance) group_left(application_id) (0 * kafka_stream_client_state{instance=~\"${instance}\", job=~\"${job}\", application_id=~\"${application}\"}))",
     "legendFormat": "{{application_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(task_id, thread_id, instance, job, cluster_type, job) (kafka_stream_task_process_total{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "avg without(thread_id, instance) (kafka_stream_task_process_rate{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",job=~\"${job}\"} + on (job, instance) group_left(application_id) (0 * kafka_stream_client_state{instance=~\"${instance}\", job=~\"${job}\", application_id=~\"${application}\"}))",
     "legendFormat": "{{application_id}} | {{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(task_id, thread_id, instance, job, job, cluster_type) (kafka_stream_task_process_rate{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avg without(thread_id, instance) (kafka_stream_task_process_latency_avg{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",job=~\"${job}\"} + on (job, instance) group_left(application_id) (0 * kafka_stream_client_state{instance=~\"${instance}\", job=~\"${job}\", application_id=~\"${application}\"}))/1000000",
     "legendFormat": "{{application_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "process latency (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(task_id, thread_id, instance, job, job, cluster_type) (kafka_stream_task_process_latency_avg{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", job=~\"${job}\"})/1000000",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "record lateness (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg without(task, thread_id, instance)  (kafka_stream_task_record_lateness_avg{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",job=~\"${job}\"} + on (job, instance) group_left(application_id) (0 * kafka_stream_client_state{instance=~\"${instance}\", job=~\"${job}\", application_id=~\"${application}\"}) >= 0)",
     "legendFormat": "{{application_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "record lateness (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg without(task_id, thread_id, instance, job, job) (kafka_stream_task_record_lateness_avg{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "records dropped total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum without(task, thread_id, instance)  (kafka_stream_task_dropped_records_total{task_id=~\"${task}_${partition}\",thread_id=~\"${thread}\",instance=~\"${instance}\",job=~\"${job}\"} + on (job, instance) group_left(application_id) (0 * kafka_stream_client_state{instance=~\"${instance}\", job=~\"${job}\", application_id=~\"${application}\"}) >= 0)",
     "legendFormat": "{{application_id}}|{{task_id}}"
    }
   ]
  },
  {
   "title": "records dropped total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum without(task_id, thread_id, instance, job, job, cluster_type) (kafka_stream_task_dropped_records_total{task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\",instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}