{
 "title": "04 - Streams - Processes",
 "tags": [ "streams" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\"}, cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\", cluster_id=~\"$cluster\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_streams_stream_thread_metrics_task_created_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_rate{cluster_id=~\"$cluster\", instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values(kafka_streams_stream_task_metrics_process_rate{instance=~\"${instance}\",thread_id=~\"${thread}\"}, partition_id)"
    }
   },
   {
    "name": "process",
    "label": "process",
    "query": {
     "query": "label_values(kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{cluster_type=\"streams\",cluster_id=~\"${cluster}\",instance=~\"${instance}\", thread_id=~\"${thread}\", task_id=~\"${task}\"}, processor_node_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance, thread_id, partition_id) (kafka_streams_stream_processor_node_metrics_process_total{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{processor_node_id}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "process total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "sum  (kafka_streams_stream_processor_node_metrics_process_total{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance, thread_id, partition_id) (kafka_streams_stream_processor_node_metrics_process_rate{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{processor_node_id}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "expr": "sum  (kafka_streams_stream_processor_node_metrics_process_rate{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance, thread_id, partition_id) (kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{processor_node_id}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "e2e latency (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg  ((kafka_streams_stream_processor_node_metrics_record_e2e_latency_avg{partition_id=~\"${partition}\", processor_node_id=~\"${process}\", task_id=~\"${task}\", thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}