{
 "title": "06 - Processes",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"$source\"},job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_client_state{job=~\"${job}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"${job}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_stream_processor_node_process_rate{job=~\"$job\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "task",
    "label": "task",
    "query": {
     "query": "label_values(kafka_stream_processor_node_process_rate{job=~\"$job\", instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   },
   {
    "name": "partition",
    "label": "partition",
    "query": {
     "query": "label_values(kafka_stream_processor_node_process_rate{instance=~\"${instance}\",thread_id=~\"${thread}\"}, task_id)"
    }
   },
   {
    "name": "process",
    "label": "process",
    "query": {
     "query": "query_result(kafka_stream_processor_node_process_rate{cluster_type=\"streams\",job=~\"${job}\",instance=~\"${instance}\", thread_id=~\"${thread}\", task_id=~\"${task}_${partition}\"} or kafka_stream_processor_node_suppression_emit_rate{cluster_type=\"streams\",job=~\"${job}\",instance=~\"${instance}\", thread_id=~\"${thread}\", task_id=~\"${task}_${partition}\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "process total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum without(instance, thread_id) (kafka_stream_processor_node_process_total{processor_node_id=~\"${process}\", task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{processor_node_id}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "process total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "msgs" } },
   "targets": [
    {
     "expr": "sum  (kafka_stream_processor_node_process_total{processor_node_id=~\"${process}\", task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum without(instance, thread_id) (kafka_stream_processor_node_process_rate{ processor_node_id=~\"${process}\", task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{processor_node_id}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "process rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum  (kafka_stream_processor_node_process_rate{processor_node_id=~\"${process}\", task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{task_id}}"
    }
   ]
  },
  {
   "title": "e2e latency (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum without(instance, thread_id) (kafka_stream_processor_node_record_e2e_latency_avg{processor_node_id=~\"${process}\", task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"})",
     "legendFormat": "{{processor_node_id}} ({{task_id}})"
    }
   ]
  },
  {
   "title": "e2e latency (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg  ((kafka_stream_processor_node_record_e2e_latency_avg{processor_node_id=~\"${process}\", task_id=~\"${task}_${partition}\", thread_id=~\"${thread}\", instance=~\"${instance}\", job=~\"${job}\"}) >=0)",
     "legendFormat": "{{task_id}}"
    }
   ]
  }
 ]
}