{
 "title": "08 - StateStore (put/fetch)",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\"}, job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_client_state{job=~\"${job}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"${job}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_stream_thread_process_rate{job=~\"$job\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "store_type",
    "query": {
     "query": "label_values({job=~\"$job\", instance=~\"$instance\", thread_id=~\"$thread\", __name__=~\"kafka_stream_state_.+\"},store_type)"
    }
   },
   {
    "name": "state",
    "label": "state",
    "query": {
     "query": "label_values({instance=~\"${instance}\", thread_id=~\"${thread}\", __name__=~\"kafka_stream_state_(.+)\"},state_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "put-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_stream_state_put_rate{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "get|fetch-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_stream_state_fetch_rate{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    },
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_stream_state_get_rate{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "remove|delete-rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id, thread_id,instance) (kafka_stream_state_remove_rate{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}) > 0)",
     "legendFormat": "{{state_id}}"
    },
    {
     "expr": "sort (sum without(task_id, thread_id,instance) (kafka_stream_state_delete_rate{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}) > 0)",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "restore-rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id, thread_id,instance) (kafka_stream_state_restore_rate{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "estimage-num-keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_stream_state_estimate_num_keys{thread_id=~\"$thread\", instance=~\"$instance\", job=~\"$job\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  }
 ]
}