{
 "title": "10 - StateStore (put/fetch)",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\"}, cluster_id)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_streams_info{cluster_id=~\"${cluster}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_streams_info{cluster_type=\"streams\", cluster_id=~\"${cluster}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_streams_stream_thread_metrics_task_created_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "store_type",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics{cluster_id=~\"$cluster\", instance=~\"$instance\", thread_id=~\"$thread\"},store_type)"
    }
   },
   {
    "name": "state",
    "label": "state",
    "query": {
     "query": "label_values(kafka_streams_stream_state_metrics{instance=~\"${instance}\",thread_id=~\"${thread}\"},state_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "put-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"put-rate\", thread_id=~\"$thread\", instance=~\"$instance\", cluster_id=~\"$cluster\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "get|fetch-rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=~\"fetch-rate|get-rate\", thread_id=~\"$thread\", instance=~\"$instance\", cluster_id=~\"$cluster\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "remove-rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id, thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"remove-rate\", thread_id=~\"$thread\", instance=~\"$instance\", cluster_id=~\"$cluster\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "estimage-num-keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sort (sum without(task_id,thread_id,instance) (kafka_streams_stream_state_metrics{metric=\"estimate-num-keys\", thread_id=~\"$thread\", instance=~\"$instance\", cluster_id=~\"$cluster\", store_type=~\"$store_type\", state_id=~\"$state\"}))",
     "legendFormat": "{{state_id}}"
    }
   ]
  }
 ]
}