{
 "title": "13 - Topics Combined",
 "tags": [ "streams" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"$source\"},job)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\"}, job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_client_state{job=~\"${job}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"${job}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_stream_topic_bytes_consumed_total{job=~\"$job\", instance=~\"$instance\"}, thread_id)"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_stream_topic_bytes_produced_total{instance=~\"${instance}\", thread_id=~\"${thread}\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Produced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Metrics",
     "type": "timeseries",
     "description": "While application, instance, and thread filters will impact topics displayed, broker metrics cannot be filtered by client selection.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum by (topic) (kafka_server_brokertopicmetrics_oneminuterate{job=~\"$kafka_cluster\", name=\"MessagesInPerSec\",topic =~ \"${topic}\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Producer Metrics",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_topic_record_send_total{cluster_type=\"streams\", job=~\"$job\", instance=~\"$instance\", client_id=~\"${thread}-producer\", topic=~\"$topic\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Streams Metric",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_stream_topic_records_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\",processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes Produced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Metrics",
     "type": "timeseries",
     "description": "While application, instance, and thread filters will impact topics displayed, broker metrics cannot be filtered by client selection.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{job=~\"$kafka_cluster\", name=\"BytesInPerSec\",topic =~ \"${topic}\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Producer Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_producer_topic_byte_total{job=~\"$job\", instance=~\"$instance\", topic=~\"$topic\"}[$__rate_interval])) by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Streams Metrics",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(topic,) (rate(kafka_stream_topic_bytes_produced_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages Consumed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Metrics",
     "type": "text",
     "description": "message based consumer metrics not avaialble from the broker.",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
     "options": { "content": "__n/a__" }
    },
    {
     "title": "Consumer Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum by (topic) (rate(kafka_consumer_fetch_manager_records_consumed_total{topic=~\"$topic\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Stream Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_stream_topic_records_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\", processor_node_id=~\".+\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes Consumed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker Metrics",
     "type": "timeseries",
     "description": "While application, instance, and thread filters will impact topics displayed, broker metrics cannot be filtered by client selection.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum without(instance,job)(kafka_server_brokertopicmetrics_oneminuterate{job=~\"$kafka_cluster\", name=\"BytesOutPerSec\",topic =~ \"${topic}\"})",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Consumer Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(kafka_consumer_fetch_manager_bytes_consumed_total{topic=~\"$topic\", job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Stream Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by(topic) (rate(kafka_stream_topic_bytes_consumed_total{job=~\"${job}\",instance=~\"${instance}\",thread_id=~\"${thread}\", task_id=~\".+_.+\", topic=~\"${topic}\"}[$__rate_interval]))",
       "legendFormat": "{{topic}} "
      }
     ]
    }
   ]
  }
 ]
}