{
 "title": "14 - Core Insights",
 "tags": [ "streams" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=~\"$source\"},job)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_stream_client_state{job=\"$job\"},application_id)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(kafka_stream_client_state{cluster_type=\"streams\", job=\"$job\", application_id=\"$application\"},instance)"
    }
   },
   {
    "name": "thread",
    "query": {
     "query": "label_values(kafka_stream_thread_process_rate{job=\"$job\", instance=~\"$instance\"},thread_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "End-2-end latency",
   "type": "stat",
   "description": "How long it takes to process a record as perceived by users. It’s the difference between the record timestamp and the time at which the record was fully processed by the Kafka Streams processor node. So it shows not only how long it took for Kafka Streams to process the record, but also how long it took for Kafka Streams to pick up the record. ",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "max(kafka_stream_processor_node_record_e2e_latency_avg{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kafka_stream_processor_node_record_e2e_latency_max{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Process latency",
   "type": "stat",
   "description": "Execution time to process records.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "max(kafka_stream_thread_process_latency_avg{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kafka_stream_thread_process_latency_max{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Process Rate",
   "type": "stat",
   "description": "how many records are being processed per second.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_stream_task_process_rate{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "How many instances are active",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  group by (instance) (kafka_stream_client_state{job=\"$job\", application_id=\"$application\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "How many threads are active",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  group by (thread_id) (kafka_stream_thread_process_rate{job=\"$job\", instance=~\"$instance\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks",
   "type": "stat",
   "description": "How many tasks are active",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  group by (task_id) (kafka_stream_task_process_rate{job=\"$job\", instance=~\"$instance\"})\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages in",
   "type": "bargauge",
   "description": "The rate at which Kafka Streams source nodes are consuming messages from Kafka topics.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_stream_topic_records_consumed_total{job=~\"${job}\",thread_id=~\"${thread}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Messages out",
   "type": "bargauge",
   "description": "The rate at which Kafka Streams sink nodes are producing messages to Kafka topics.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(kafka_stream_topic_records_produced_total{job=~\"${job}\",thread_id=~\"${thread}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Punctuation rate",
   "type": "stat",
   "description": "The rate at which punctuators are triggered.",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "/minute" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_stream_thread_punctuate_rate{job=~\"$job\", thread_id=~\"$thread\"}) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "barchart",
   "description": "An overview of how Kafka Streams spends its execution time. Active actions are processing messages, punctuating and committing. The remaining time is typically spend polling for data.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(instance, thread_id) (avg_over_time(kafka_stream_thread_process_ratio{job=~\"$job\", thread_id=~\"$thread\"}[$__interval]) <= +Inf)",
     "legendFormat": "process ratio"
    },
    {
     "expr": "avg without(instance, thread_id) (avg_over_time(kafka_stream_thread_punctuate_ratio{job=~\"$job\", thread_id=~\"$thread\"}[$__interval]) <= +Inf)",
     "legendFormat": "punctuate ratio"
    },
    {
     "expr": "avg without(instance, thread_id) (avg_over_time(kafka_stream_thread_commit_ratio{job=~\"$job\", thread_id=~\"$thread\"}[$__interval]) <= +Inf)",
     "legendFormat": "commit ratio"
    }
   ]
  },
  {
   "title": "Punctuation latency",
   "type": "stat",
   "description": "The average and maximum execution time across all punctuators",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "max(kafka_stream_thread_punctuate_latency_avg{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kafka_stream_thread_punctuate_latency_max{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Max"
    }
   ]
  },
  { "title": "State Stores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Estimated keys in state stores",
   "type": "bargauge",
   "description": "How many keys are stored in the state stores. Every task maintains its own part of a state store. This panel shows the sum of those keys, for every state store.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state_id) (kafka_stream_state_estimate_num_keys{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memtables size by state store",
   "type": "bargauge",
   "description": "Off-heap memory used for RocksDB’s memtables, summed by Kafka Streams state store. \nRocksDB buffers writes into these memtables as new records are put into the state store. Every RocksDB store by default has 3 active memtables, of 16MB each. These memtables get flushed as they fill up. When it reaches the maximum (48MB for all 3 memtables combined), there might be performance issues with flushing the memtables to disk. ",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state_id) (kafka_stream_state_cur_size_all_mem_tables{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "Block cache usage by state store",
   "type": "bargauge",
   "description": "Off-heap memory used for RocksDB’s block cache, summed by Kafka Streams state store. This cache is used by RocksDB to efficiently process read requests, without having to read data from disk. If it reaches the default of 50MB per RocksDB store, then you might have to increase it for better read performance. When increasing it, watch out for the memory configuration of your server/container to avoid OOM issues, as this is off-heap memory.",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(state_id) (kafka_stream_state_block_cache_usage{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "{{state_id}}"
    }
   ]
  },
  {
   "title": "Open iterators",
   "type": "stat",
   "description": "The current number of iterators on a state store that have been created, but not yet closed. If this keeps going up, then you probably didn’t close a state store iterator in your code and have a memory leak.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_stream_state_num_open_iterators{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Iterator duration",
   "type": "stat",
   "description": "The average time spent between creating an iterator and closing it.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "p95" ] } },
   "targets": [
    {
     "expr": "max(kafka_stream_state_iterator_duration_avg{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(kafka_stream_state_iterator_duration_max{job=\"$job\", thread_id=\"$thread\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "State store GET rate",
   "type": "timeseries",
   "description": "The rate of GET operations on the state stores.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "targets": [
    {
     "expr": "sum by(state_id) (kafka_stream_state_get_rate{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State store PUT rate",
   "type": "timeseries",
   "description": "The rate of PUT operations on the state stores.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "targets": [
    {
     "expr": "sum by(state_id) (kafka_stream_state_put_rate{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State store DELETE rate",
   "type": "timeseries",
   "description": "The rate of DELETE operations on the state stores.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "/sec" } },
   "targets": [
    {
     "expr": "sum by(state_id) (kafka_stream_state_delete_rate{job=~\"$job\", thread_id=~\"$thread\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}