
lowercaseOutputName: true
rules:
#- pattern: kafka.(.*)
- pattern: java.lang<type=(.*)>
- pattern: "kafka.server<type=app-info, id=(.+)><>(.*): (.*)"
  name: kafka_server_app_info_$2
  labels:
    node_id: "$1"
    kafka_version: "$3"
  value: 1
- pattern: "kafka.server<type=raft-metrics><>current-state: (.+)"
  name: kafka_server_raft_metrics_current_state
  labels:
    state: $1
  value: 1
- pattern: "kafka.server<type=raft-metrics><>(.+): (.+)"
- pattern: kafka.server<type=SnapshotEmitter, name=LatestSnapshotGeneratedBytes>
- pattern: kafka.cluster<type=Partition, name=UnderReplicated, topic=(.+), partition=(.+)><>Value
- pattern: kafka.controller<type=KafkaController, name=ActiveControllerCount><>Value
- pattern: kafka.controller<type=KafkaController, name=OfflinePartitionsCount><>Value
- pattern: kafka.controller<type=ControllerStats, name=UncleanLeaderElectionsPerSec><>Count
- pattern: kafka.controller<type=ControllerStats, name=UncleanLeaderElectionsPerSec><>OneMinuteRate
- pattern: kafka.log<type=Log, name=(.+), topic=(.+), partition=(.+)><>Value
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>999thPercentile
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>99thPercentile
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>95thPercentile
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>75thPercentile
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+)><>50thPercentile
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+), version=(.+)><>Count
- pattern: kafka.network<type=RequestMetrics, name=(.+), request=(.+), version=(.+)><>OneMinuteRate
- pattern: kafka.network<type=RequestChannel, name=(.+)><>Value
- pattern: kafka.network<type=RequestChannel, processor=(.+), name=(.+)><>Value
- pattern: kafka.server<type=ReplicaManager, name=LeaderCount><>Value
- pattern: kafka.server<type=ReplicaManager, name=PartitionCount><>Value
- pattern: kafka.server<type=ReplicaManager, name=UnderReplicatedPartitions><>Value
- pattern: kafka.server<type=ReplicaManager, name=IsrExpandsPerSec><>Count
- pattern: kafka.server<type=ReplicaManager, name=IsrExpandsPerSec><>OneMinuteRate
- pattern: kafka.server<type=ReplicaFetcherManager, name=MaxLag, clientId=(.+)><>Value
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesOutPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesOutPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesInPerSec, topic=(.+)><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesOutPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=MessagesOutPerSec, topic=(.+)><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesInPerSec, topic=(.+)><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BytesOutPerSec, topic=(.+)><>OneMinuteRate
- pattern: kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>Count
- pattern: kafka.server<type=KafkaRequestHandlerPool, name=RequestHandlerAvgIdlePercent><>OneMinuteRate
- pattern: kafka.server<type=socket-server-metrics, clientSoftwareName=(.+), clientSoftwareVersion=(.+), listener=(.+), networkProcessor=(.+)><>connections
- pattern: kafka.server<type=socket-server-metrics, listener=(.+), networkProcessor=(.+)><>(.+)
- pattern: kafka.server<type=DelayedOperationPurgatory, name=PurgatorySize, delayedOperation=(.+)><>Value

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchBytesPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchBytesPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchBytesPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchBytesPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchRequestsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchRequestsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchRequestsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchRequestsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchErrorsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchErrorsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchErrorsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteFetchErrorsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyBytesPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyBytesPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyBytesPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyBytesPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyRequestsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyRequestsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyRequestsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyRequestsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyErrorsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyErrorsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyErrorsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyErrorsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteRequestsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteRequestsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteRequestsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteRequestsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteErrorsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteErrorsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteErrorsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteErrorsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateRequestsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateRequestsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateRequestsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateRequestsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateErrorsPerSec><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateErrorsPerSec><>OneMinuteRate
- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateErrorsPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=BrokerTopicMetrics, name=BuildRemoteLogAuxStateErrorsPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=DelayedRemoteFetchMetrics, name=ExpiresPerSec, topic=(.+)><>Count
- pattern: kafka.server<type=DelayedRemoteFetchMetrics, name=ExpiresPerSec, topic=(.+)><>OneMinuteRate

- pattern: kafka.server<type=DelayedRemoteListOffsetsMetrics, name=ExpiresPerSec, topic=(.+), partition=(.+)><>Count
- pattern: kafka.server<type=DelayedRemoteListOffsetsMetrics, name=ExpiresPerSec, topic=(.+), partition=(.+)><>OneMinuteRate

- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyLagBytes, topic=(.+)><>Value
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteCopyLagSegments, topic=(.+)><>Value
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteDeleteLagBytes, topic=(.+)><>Value
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteLogSizeComputationTime, topic=(.+)><>Value
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteLogSizeBytes, topic=(.+)><>Value
- pattern: kafka.server<type=BrokerTopicMetrics, name=RemoteLogMetadataCount, topic=(.+)><>Value

- pattern: org.apache.kafka.storage.internals.log<type=RemoteStorageThreadPool, name=RemoteLogReaderTaskQueueSize><>Value
- pattern: org.apache.kafka.storage.internals.log<type=RemoteStorageThreadPool, name=RemoteLogReaderAvgIdlePercent><>Value

- pattern: kafka.log.remote<type=RemoteLogManager, name=RemoteLogManagerTasksAvgIdlePercent><>Value
- pattern: kafka.log.remote<type=RemoteLogManager, name=RemoteLogReaderFetchRateAndTimeMs><>Value

- pattern: kafka.server<type=RemoteLogManager, name=remote-fetch-throttle-time-avg><>Value
- pattern: kafka.server<type=RemoteLogManager, name=remote-fetch-throttle-time-max><>Value
- pattern: kafka.server<type=RemoteLogManager, name=remote-copy-throttle-time-avg><>Value
- pattern: kafka.server<type=RemoteLogManager, name=remote-copy-throttle-time-max><>Value