apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    editable: false

  - name: tempo
    type: tempo
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
#      tracesToLogs:
#        datasourceUid: 'loki'
#        tags: ['job', 'instance' ]
#        mappedTags: [{ key: 'service.name', value: 'service' }]
#        mapTagNamesEnabled: false
#        spanStartTimeShift: '1h'
#        spanEndTimeShift: '1h'
#        filterByTraceID: false
#        filterBySpanID: false
#      tracesToMetrics:
#        datasourceUid: 'prom'
#        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
#        queries:
#          - name: 'Sample query'
#            query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
#      search:
#        hide: false
      nodeGraph:
        enabled: true
#      lokiSearch:
#        datasourceUid: 'loki'
