{
 "title": "02 - Threads - A",
 "tags": [ "streams" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(jvm_info{cluster_type=\"streams\"}, cluster_id)"
    }
   },
   {
    "name": "application",
    "query": {
     "query": "label_values(kafka_streams_info{cluster_id=~\"${cluster}\", application_id=~\".+\"}, application_id)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_streams_info{cluster_type=\"streams\", cluster_id=~\"${cluster}\", application_id=~\"$application\"}, instance)"
    }
   },
   {
    "name": "thread",
    "label": "thread",
    "query": {
     "query": "label_values(kafka_streams_stream_thread_metrics_task_created_total{cluster_id=~\"$cluster\", instance=~\"$instance\"}, thread_id)"
    }
   },
   { "name": "measurement", "query": "commit,poll,process,punctuate" }
  ]
 },
 "panels": [
  {
   "title": "${measurement} total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(cluster_id,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_total{cluster_id=~\"${cluster}\", instance=~\"${instance}\", thread_id=~\"${thread}\"} * on (cluster_id, instance) group_left(application_id) kafka_streams_info{application_id=~\"${application}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_thread_metrics_${measurement}_total{cluster_id=~\"${cluster}\", instance=~\"${instance}\", thread_id=~\"${thread}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(cluster_id,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_rate{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_streams_stream_thread_metrics_${measurement}_rate{cluster_id=~\"${cluster}\", instance=~\"${instance}\", thread_id=~\"${thread}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate (grafana computed)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(cluster_id,instance,thread) (rate(kafka_streams_stream_thread_metrics_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"}[$__rate_interval]))",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} rate (grafana computed)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (rate(kafka_streams_stream_thread_metrics_${measurement}_total{thread_id=~\"${thread}\", instance=~\"${instance}\", cluster_id=~\"${cluster}\"}[$__rate_interval]))",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(cluster_id,instance,thread) ((kafka_streams_stream_thread_metrics_${measurement}_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg ((kafka_streams_stream_thread_metrics_${measurement}_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(job,instance,thread) ((kafka_streams_stream_thread_metrics_${measurement}_latency_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >= 0)",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg ((kafka_streams_stream_thread_metrics_${measurement}_latency_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >= 0)",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} records (avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(cluster_id,instance,thread) (kafka_streams_stream_thread_metrics_${measurement}_records_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} records (avg)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg (kafka_streams_stream_thread_metrics_${measurement}_records_avg{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"})",
     "legendFormat": "{{thread_id}}"
    }
   ]
  },
  {
   "title": "${measurement} ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg without(cluster_id,instance,thread) ((kafka_streams_stream_thread_metrics_commit_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{thread_id}} (commit)"
    },
    {
     "expr": "avg without(cluster_id,instance,thread) ((kafka_streams_stream_thread_metrics_poll_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{thread_id}} (poll)"
    },
    {
     "expr": "avg without(cluster_id,instance,thread) ((kafka_streams_stream_thread_metrics_process_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{thread_id}} (process)"
    },
    {
     "expr": "avg without(cluster_id,instance,thread) ((kafka_streams_stream_thread_metrics_punctuate_ratio{instance=~\"${instance}\", thread_id=~\"${thread}\", cluster_id=~\"${cluster}\"}) >=0)",
     "legendFormat": "{{thread_id}} (punctuate)"
    }
   ]
  }
 ]
}