#!/bin/bash

kafka-configs --zookeeper localhost:2181 --alter --add-config 'SCRAM-SHA-256=[password=kafkabroker1-secret],SCRAM-SHA-512=[password=kafkabroker1-secret]' --entity-type users --entity-name kafkabroker1

