security.protocol=SSL
ssl.truststore.location=./secrets/kafka.server.truststore.jks
ssl.truststore.password=broker_secret
ssl.keystore.location=./secrets/ssl-broker-1.keystore.jks
ssl.keystore.password=broker_secret
ssl.key.password=broker_secret