lowercaseOutputName: true
rules:
- pattern: java.lang<type=(.*)>
- pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_producer_producer_metrics_$2
  labels:
    client_id: "$1"
- pattern: kafka.consumer<type=consumer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_consumer_consumer_metrics_$2
  labels:
    client_id: "$1"
- pattern: "kafka.streams<type=stream-metrics, client-id=(.+)><>(.*): (.+)"
  name: kafka_streams_info
  value: 1
  labels:
    client_id: $1
    "$2": "$3"
- pattern: kafka.streams<type=kafka-metrics-count><>(.+):.+
- pattern: kafka.streams<type=stream-record-cache-metrics, thread-id=(.+), task-id=(.+), record-cache-id=(.+)><>(.+):.+
  name: kafka_streams_stream_record_cache_metrics
  labels:
    thread_id: "$1"
    task_id: "$2"
    record-cache-id: "$3"
    metric: "$4"
- pattern: kafka.streams<type=stream-state-metrics, thread-id=(.+), task-id=(.+), (.+)-id=(.+)><>(.+):.+
  name: kafka_streams_stream_state_metrics
  labels:
    thread_id: "$1"
    task_id: "$2"
    store_type: "$3"
    state_id: "$4"
    metric: "$5"
- pattern: kafka.streams<type=stream-thread-metrics, thread-id=(.+)><>(.+):.+
  name: kafka_streams_stream_thread_metrics_$2
  labels:
    thread_id: "$1"
- pattern: kafka.streams<type=stream-task-metrics, thread-id=(.*), task-id=(.+)><>(.+):.+
  name: kafka_streams_stream_task_metrics_$3
  labels:
    thread_id: "$1"
    task_id: "$2"
- pattern: kafka.streams<type=stream-processor-node-metrics, thread-id=(.*), task-id=(.+), processor-node-id=(.+)><>(.+):.+
  name: kafka_streams_stream_processor_node_metrics_$4
  labels:
    thread_id: "$1"
    task_id: "$2"
    processor_node_id: "$3"
- pattern: kafka.streams<type=stream-topic-metrics, thread-id=(.*), task-id=(.+), processor-node-id=(.+), topic=(.+)><>(.+):.+
  name: kafka_streams_stream_topic_metrics_$5
  labels:
    thread_id: "$1"
    task_id: "$2"
    topic: "$3"
    processor_node_id: "$4"
- pattern: kafka.producer<type=producer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_producer_producer_metrics_$2
  labels:
    client_id: "$1"
- pattern: kafka.consumer<type=consumer-metrics, client-id=(.+)><>(.+):.+
  name: kafka_consumer_consumer_metrics_$2
  labels:
    client_id: "$1"
#- pattern: application(.*)
#- pattern: application<type=(.*)>
#- pattern: kafka.(.*)
