# Define the default target
.PHONY: all
all: build

# Build the project using Cargo
.PHONY: build
build:
	cargo build --release

# Clean the project using Cargo
.PHONY: clean
clean:
	cargo clean

# Run the project using Cargo
.PHONY: run
run:
	cargo run
