{
 "title": "01 - Overview",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "producer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_producer_connection_count{job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_producer_connection_count{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (kafka_producer_connection_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Client Versions",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_producer_app_infor{job=~\"$job\",instance=~\"$instance\"} > 0) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_producer_connection_count{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Compression rate",
   "type": "stat",
   "description": "non-compressed not included.",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg (kafka_producer_compression_rate_avg{job=~\"$job\", instance=~\"$instance\"} < 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_producer_record_retry_rate{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Record Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_producer_record_error_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Average Record Queue Time (send buffer)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_record_queue_time_avg{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Buffer Available",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Throttle Time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_producer_produce_throttle_time_avg{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}