{
 "title": "05 - Network",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "producer" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_producer_connection_count{job=~\"$source\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(kafka_producer_connection_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_producer_connection_count{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Select Rate",
   "type": "timeseries",
   "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_select_rate{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "IO Duration / Select Call",
   "type": "timeseries",
   "description": "\n",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_io_time_ns_avg{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "IO Wait time average",
   "type": "timeseries",
   "description": "The average length of time the I/O thread spent waiting for a socket ready for reads or writes in nanoseconds.\n",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "kafka_producer_io_wait_time_ns_avg{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "1 - IO Ratio - IO Wait Ratio",
   "type": "timeseries",
   "description": "1 indicates that the producer is the bottleneck",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg (1 - kafka_producer_io_ratio{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"} - kafka_producer_io_wait_ratio{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}) by (instance, client_id)",
     "legendFormat": "{{instance}} ({{client_id}})"
    }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "timeseries",
   "description": "The fraction of time the I/O thread spent doing I/O.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_io_ratio{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "IO Wait Ratio",
   "type": "timeseries",
   "description": "The fraction of time the I/O thread spent waiting.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_io_wait_ratio{job=~\"$job\", instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Metadata max age",
   "type": "timeseries",
   "description": "The age in seconds of the current producer metadata being used.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_producer_metadata_age{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{client_id}} ({{instance}})"
    }
   ]
  }
 ]
}