{
 "title": "01 - Clients -- Consumer (required)",
 "description": "Kafka Consumer - client metrics",
 "tags": [ "clients" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "client_id",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_consumer_connection_creation_total,client_id)"
    }
   },
   {
    "name": "principal",
    "label": "principal",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_consumer_connection_creation_total{client_id=~\"$client_id\"},principal)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Defect preventing -- waiting for AK 4.0",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n* always reported as NaN, defect.\n\n* https://issues.apache.org/jira/browse/KAFKA-17230\n\n"
   }
  },
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(client_id, node_id, principal) (kafka_clients_org_apache_kafka_consumer_node_request_latency_avg{client_id=~\"$client_id\", principal=~\"$principal\"} >= 0)",
     "legendFormat": "{{client_id}} {{node_id}} ({{principal}})"
    }
   ]
  },
  {
   "title": "Request Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(client_id, node_id, principal) (kafka_clients_org_apache_kafka_consumer_node_request_latency_max{client_id=~\"$client_id\", principal=~\"$principal\"} >= 0)",
     "legendFormat": "{{client_id}} {{node_id}} ({{principal}})"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "cxs" } },
   "targets": [
    {
     "expr": "sum by(client_id, client_instance_id, principal) (last_over_time(kafka_clients_org_apache_kafka_consumer_connection_creation_total{client_id=~\"$client_id\", principal=~\"$principal\"}[1m]))",
     "legendFormat": "{{client_id}} ({{client_instance_id}})"
    }
   ]
  }
 ]
}