{
 "title": "01 - Clients -- Producer (required)",
 "description": "Kafka Producer - client metrics",
 "tags": [ "clients" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "client_id",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_producer_connection_creation_total,client_id)"
    }
   },
   {
    "name": "principal",
    "label": "principal",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_producer_connection_creation_total{client_id=~\"$client_id\"},principal)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Latency (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(client_id, client_instance_id, client_source_address, node_id, principal) (kafka_clients_org_apache_kafka_producer_node_request_latency_avg{client_id=~\"$client_id\", principal=~\"$principal\"} >= 0)",
     "legendFormat": "{{client_id}} / {{client_source_address}} ({{principal}}) | {{node_id}} "
    }
   ]
  },
  {
   "title": "Request Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(client_id, node_id, principal) (kafka_clients_org_apache_kafka_producer_node_request_latency_max{client_id=~\"$client_id\", principal=~\"$principal\"} >= 0)",
     "legendFormat": "{{client_id}} / {{client_source_address}} ({{principal}}) | {{node_id}} "
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cxs" } },
   "targets": [
    {
     "expr": "sum by(client_id, client_instance_id, client_source_address, principal) (last_over_time(kafka_clients_org_apache_kafka_producer_connection_creation_total{client_id=~\"$client_id\", principal=~\"$principal\"}[1m]))",
     "legendFormat": "{{client_id}} / {{client_source_address}} ({{principal}})"
    }
   ]
  }
 ]
}