{
 "title": "02 - Clients - Consumer Overview",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "clients" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "client_software_name",
    "label": "client_software_name",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_consumer_node_request_latency_avg,client_software_name)"
    }
   },
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_consumer_node_request_latency_avg{client_software_name=~\"$client_software_name\"},client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (kafka_clients_org_apache_kafka_consumer_connection_count{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"} > 0)",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Client Versions",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_clients_org_apache_kafka_consumer_connection_count{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"} > 0) by (client_software_name, client_software_version) ",
     "legendFormat": "{{client_software_name}}-{{client_software_version}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_clients_org_apache_kafka_consumer_connection_count{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"})",
     "legendFormat": "{{client_id}}@{{hostname}}"
    }
   ]
  },
  {
   "title": "Commit Calls / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_clients_org_apache_kafka_consumer_coordinator_commit_rate{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalance rate per hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (kafka_clients_org_apache_kafka_consumer_coordinator_rebalance_rate_per_hour{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"} + kafka_clients_org_apache_kafka_consumer_coordinator_failed_rebalance_rate_per_hour{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_clients_org_apache_kafka_consumer_coordinator_rebalance_total{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"} + kafka_clients_org_apache_kafka_consumer_coordinator_failed_rebalance_total{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Responses / second",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum (kafka_clients_org_apache_kafka_consumer_node_response_rate{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"} > 0) by (client_instance_id, client_source_address, client_id)",
     "legendFormat": "{{client_id}} / {{client_source_address}}"
    }
   ]
  },
  {
   "title": "Throttle Time (avg)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(kafka_clients_org_apache_kafka_consumer_fetch_manager_fetch_throttle_time_avg{client_software_name=~\"$client_software_name\", client_id=~\"$client_id\"} >= 0)",
     "legendFormat": "{{client_id}} ({{client_source_address}})"
    }
   ]
  }
 ]
}