{
 "title": "03 - Clients - Producer Throughput",
 "description": "Java client Kafka Producer metrics",
 "tags": [ "clients" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   {
    "name": "client_id",
    "label": "client-id",
    "query": {
     "query": "label_values(kafka_clients_org_apache_kafka_producer_connection_count,client_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Outgoing Messages / second (client)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(kafka_clients_org_apache_kafka_producer_record_send_total{client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate (client)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(kafka_clients_org_apache_kafka_producer_outgoing_byte_total{client_id=~\"$client_id\"}[$__rate_interval])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing messages / second (topic)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_clients_org_apache_kafka_producer_topic_record_send_total{client_id=~\"$client_id\", topic=~\".+\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate (topic)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_clients_org_apache_kafka_producer_topic_byte_total{client_id=~\"$client_id\", topic=~\".+\"}[$__rate_interval])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}