global:
  scrape_interval: 2s

scrape_configs:

  - job_name: zookeeper
    scrape_interval: 30s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'zookeeper'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - replacement: 'zookeeper'
        target_label: cluster_type
      - replacement: 'kafka-zookeeper'
        target_label: job

  - job_name: kafka
    scrape_interval: 30s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'controller-0'
          - 'controller-1'
          - 'controller-2'
          - 'broker-1'
          - 'broker-2'
          - 'broker-3'
          - 'broker-4'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - replacement: 'kafka'
        target_label: cluster_type

  - job_name: kafka-sasl
    scrape_interval: 30s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'sasl-controller-0'
          - 'sasl-controller-1'
          - 'sasl-controller-2'
          - 'sasl-broker-1'
          - 'sasl-broker-2'
          - 'sasl-broker-3'
          - 'sasl-broker-4'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - replacement: 'kafka'
        target_label: cluster_type

  - job_name: kafka-ssl
    scrape_interval: 30s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'sasl-controller-0'
          - 'sasl-controller-1'
          - 'sasl-controller-2'
          - 'sasl-broker-1'
          - 'sasl-broker-2'
          - 'sasl-broker-3'
          - 'sasl-broker-4'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - replacement: 'kafka'
        target_label: cluster_type

  - job_name: koffset
    scrape_interval: 5s
    metrics_path: /metrics
    params:
      primary: ["true"]
    dns_sd_configs:
      - names:
          - 'koffset'
        type: 'A'
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: instance
      - replacement: 'kafka'
        target_label: cluster_type

#  - job_name: koffset
#    scrape_interval: 5s
#    metrics_path: /metrics
#    params:
#      primary: ["true"]
#    static_configs:
#      - targets:
#          - koffset:8080
#        labels:
#          job: "koffset-kafka-core"
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: '(.*):(.*)'
#        target_label: instance
#        replacement: '$1'
#
  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['otel:9091']

  - job_name: 'broker-opentelemetry'
    static_configs:
      - targets: ['broker-otel:9091']

  - job_name: 'container-info'
    static_configs:
      - targets: ['container-info:9323']

  - job_name: publishers
    scrape_interval: 2s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'publisher'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        replacement: '$1'
        target_label: address
      - replacement: 'producers'
        target_label: cluster_type
      - replacement: 'publisher'
        target_label: job
      - replacement: 'jmx'
        target_label: source
    metric_relabel_configs:
      - source_labels: [service, address]
        separator: '@'
        target_label: instance
      - regex: 'address'
        action: labeldrop

  - job_name: publisher_micrometer
    scrape_interval: 2s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'publisher'
        type: 'A'
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
      - source_labels: [__address__]
        regex: '(.*):[0-9]+'
        replacement: '$1'
        target_label: instance
      - replacement: 'producers'
        target_label: cluster_type
    metric_relabel_configs:
      - source_labels: [service, address]
        separator: '@'
        target_label: instance
      - regex: 'address'
        action: labeldrop
      # Remove the kafka_version label from all metrics (it's always the same value)
      - regex: 'kafka_version'
        action: labeldrop

  - job_name: streams
    scrape_interval: 2s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'stream'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        replacement: '$1'
        target_label: address
      - replacement: 'streams'
        target_label: cluster_type
      - replacement: 'jmx'
        target_label: source
    metric_relabel_configs:
      - source_labels: [service, address]
        separator: '@'
        target_label: instance
      - regex: 'address'
        action: labeldrop

  - job_name: streams_micrometer
    scrape_interval: 2s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'stream'
          - 'stream-native'
        type: 'A'
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
      - source_labels: [__address__]
        regex: '(.*):[0-9]+'
        replacement: '$1'
        target_label: address
      - replacement: 'streams'
        target_label: cluster_type
      - replacement: 'micrometer'
        target_label: source
    metric_relabel_configs:
      - source_labels: [service, address]
        separator: '@'
        target_label: instance
      - regex: 'address'
        action: labeldrop
      # Remove the kafka_version label from all metrics (it's always the same value)
      - regex: 'kafka_version'
        action: labeldrop
      - source_labels: [rocksdb_state_id,rocksdb_window_state_id,rocksdb_session_state_id,in_memory_state_id,in_memory_window_state_id,in_memory_lru_state_id,in_memory_suppression_state_id]
        separator: '' # ; is the default, but since only one of the source labels is ever defined, we remove this separator
        target_label: state_id
        regex: '(.+)'
        replacement: '$1'
        action: replace
      - source_labels: [rocksdb_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "rocksdb_state"
        action: replace
      - source_labels: [rocksdb_window_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "rocksdb_window_state"
        action: replace
      - source_labels: [rocksdb_session_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "rocksdb_session_state"
        action: replace
      - source_labels: [in_memory_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_state"
        action: replace
      - source_labels: [in_memory_window_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_window_state"
        action: replace
      - source_labels: [in_memory_lru_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_lru_state"
        action: replace
      - source_labels: [in_memory_suppression_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_suppression_state"
        action: replace

  - job_name: analytics
    scrape_interval: 2s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'analytics-sliding'
          - 'analytics-tumbling'
          - 'analytics-hopping'
          - 'analytics-session'
          - 'analytics-none'
        type: 'A'
        port: 7071
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        replacement: '$1'
        target_label: address
      - replacement: 'streams'
        target_label: cluster_type
      - replacement: 'jmx'
        target_label: source
    metric_relabel_configs:
      - source_labels: [service, address]
        separator: '@'
        target_label: instance
      - regex: 'address'
        action: labeldrop

  - job_name: analytics_micrometer
    scrape_interval: 2s
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - 'analytics-sliding'
          - 'analytics-tumbling'
          - 'analytics-hopping'
          - 'analytics-session'
          - 'analytics-none'
        type: 'A'
        port: 8080
    relabel_configs:
      - source_labels: [__meta_dns_name]
        target_label: service
      - source_labels: [__address__]
        regex: '(.*):[0-9]+'
        replacement: '$1'
        target_label: address
      - replacement: 'streams'
        target_label: cluster_type
      - replacement: 'micrometer'
        target_label: source
    metric_relabel_configs:
      - source_labels: [service, address]
        separator: '@'
        target_label: instance
      - regex: 'address'
        action: labeldrop
      # Remove the kafka_version label from all metrics (it's always the same value)
      - regex: 'kafka_version'
        action: labeldrop
      - source_labels: [rocksdb_state_id,rocksdb_window_state_id,rocksdb_session_state_id,in_memory_state_id,in_memory_window_state_id,in_memory_lru_state_id,in_memory_suppression_state_id]
        separator: '' # ; is the default, but since only one of the source labels is ever defined, we remove this separator
        target_label: state_id
        regex: '(.+)'
        replacement: '$1'
        action: replace
      - source_labels: [rocksdb_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "rocksdb_state"
        action: replace
      - source_labels: [rocksdb_window_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "rocksdb_window_state"
        action: replace
      - source_labels: [rocksdb_session_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "rocksdb_session_state"
        action: replace
      - source_labels: [in_memory_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_state"
        action: replace
      - source_labels: [in_memory_window_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_window_state"
        action: replace
      - source_labels: [in_memory_lru_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_lru_state"
        action: replace
      - source_labels: [in_memory_suppression_state_id]
        target_label: "store_type"
        regex: ".+"
        replacement: "in_memory_suppression_state"
        action: replace




#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']
#    metric_relabel_configs:
#      - source_labels: [id]
#        target_label: id
#        regex: '/docker/(.*)'
#        replacement: '$1'

#  - job_name: micrometer_applications
#    scrape_interval: 2s
#    metrics_path: /metrics
#    file_sd_configs:
#      - files:
#          - /etc/prometheus/micrometer_application_*.json
#    relabel_configs:
#      # an alternate way to handle 'application', useful for kafka.streams and unable to pull application.id by custom micrometer metric
##      - source_labels: [__address__]
##        regex: '[a-z]-(.*)(-[0-9])?:.*'
##        target_label: application
##        replacement: '$1'
#      - source_labels: [__address__]
#        regex: '(.*):[0-9]+'
#        target_label: instance
#        replacement: '$1'
#    metric_relabel_configs:
#      - source_labels: [rocksdb_state_id,rocksdb_window_state_id,rocksdb_session_state_id,in_memory_state_id,in_memory_window_state_id,in_memory_lru_state_id,in_memory_suppression_state_id]
#        separator: '' # ; is the default, but since only one of the source labels is ever defined, we remove this separator
#        target_label: state_id
#        regex: '(.+)'
#        replacement: '$1'
#        action: replace
#      - source_labels: [rocksdb_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "rocksdb_state"
#        action: replace
#      - source_labels: [rocksdb_window_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "rocksdb_window_state"
#        action: replace
#      - source_labels: [rocksdb_session_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "rocksdb_session_state"
#        action: replace
#      - source_labels: [in_memory_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "in_memory_state"
#        action: replace
#      - source_labels: [in_memory_window_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "in_memory_window_state"
#        action: replace
#      - source_labels: [in_memory_lru_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "in_memory_lru_state"
#        action: replace
#      - source_labels: [in_memory_suppression_state_id]
#        target_label: "store_type"
#        regex: ".+"
#        replacement: "in_memory_suppression_state"
#        action: replace


#  - job_name: kafka-lag-exporter
#    scrape_interval: 5s
#    metrics_path: /metrics
#    static_configs:
#      - targets:
#          - kafka-lag-exporter:8000
#        labels:
#          job: "kafka-lag-exporter-kafka-core"
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: '(.*):(.*)'
#        target_label: instance
#        replacement: '$1'

#  - job_name: kafka_exporter
#    static_configs:
#      - targets:
#        - kafka-exporter:9308
#        labels:
#          job: "exporter_kafka-core"
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: '(.*):(.*)'
#        target_label: instance
#        replacement: '$1'

#  - job_name: sasl_kafka_exporter
#    static_configs:
#      - targets:
#          - sasl-kafka-exporter:9308
#        labels:
#          job: "exporter_sasl-kafka-core"
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: '(.*):(.*)'
#        target_label: instance
#        replacement: '$1'

#  - job_name: applications
#    scrape_interval: 2s
#    metrics_path: /metrics
#    file_sd_configs:
#      - files:
#          - /etc/prometheus/applications.json
#    relabel_configs:
#      - source_labels: [__address__]
#        regex: '(.*):[0-9]+'
#        target_label: instance
#        replacement: '$1'
