{
 "title": "00 - Overview",
 "tags": [ "containers" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Docker Compose Project",
    "query": {
     "query": "label_values(docker_container_info{id=~\"^[a-f0-9]{64}$\"},project)"
    }
   },
   {
    "name": "service",
    "label": "Docker Compose Service",
    "query": {
     "query": "label_values(docker_container_info{id=~\"^[a-f0-9]{64}$\", project=~\"$project\"},service)"
    }
   },
   {
    "name": "container",
    "label": "Container name",
    "query": {
     "query": "label_values(docker_container_info{id=~\"^[a-f0-9]{64}$\", project=~\"$project\", service=~\"$service\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Container CPU usage (cores)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{id=~\"^[a-f0-9]{64}$\"}[1m]) * on (id) group_left(name) docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, id) (\n  container_memory_working_set_bytes{id=~\"^[a-f0-9]{64}$\"} \n  * on (id) group_left(name) \n  docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"}\n)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "sum by (name, id) (\n  (container_memory_usage_bytes{id=~\"^[a-f0-9]{64}$\"})\n  * on (id) group_left(name) \n  docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"}\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container disk I/O (reads)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_reads_bytes_total{id=~\"^[a-f0-9]{64}$\"}[1m]) * on (id) group_left(name) docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container disk I/O (writes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_fs_writes_bytes_total{id=~\"^[a-f0-9]{64}$\"}[1m]) * on (id) group_left(name) docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "JVM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "JVM heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{area=\"heap\", instance=~\".+\"} * on (instance) group_left(name) (label_replace(docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM non-heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (jvm_memory_used_bytes{area=\"nonheap\", instance=~\".+\"} * on (instance) group_left(name) (label_replace(docker_container_info{project=~\"$project\", service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}