{
 "title": "02 - Containers - Kafka Streams",
 "tags": [ "containers" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "source",
    "query": "jmx : ^[^_]+$ , micrometer : .*_micrometer"
   },
   {
    "name": "service",
    "label": "Docker Compose Service",
    "query": {
     "query": "query_result(container_info{id=~\"^[a-f0-9]{64}$\"} * on (endpoint) group_left() (label_replace(kafka_stream_client_state{job=~\"$source\"}, \"endpoint\", \"$1\", \"instance\", \"(.+)\")))"
    }
   },
   {
    "name": "container",
    "label": "Container name",
    "query": {
     "query": "label_values(container_info{id=~\"^[a-f0-9]{64}$\", service=~\"$service\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container - Working Set",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, id) (\n  container_memory_bytes{key=\"anon\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"} \n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container - Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, id) (\n  container_memory_bytes{key=\"usage\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"} \n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container - Kernel Stack",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, id) (\n  container_memory_bytes{key=\"kernel_stack\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"} \n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container & JVM Memory Breakdown - $container",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, component) (\n\n  label_replace(\n    (\n      label_replace(\n          jvm_memory_used_bytes{area=\"heap\"}\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\", \n          \"$1\", \n          \"instance\", \n          \"(.*)\")\n    ),\n    \"component\", \"01_jvm_heap_used\", \"\", \"\"\n  )\n\n  or\n\n  label_replace(\n    (\n      label_replace(\n          (jvm_memory_committed_bytes{area=\"heap\"} - jvm_memory_used_bytes{area=\"heap\"})\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\",\n          \"$1\",\n          \"instance\",\n          \"(.*)\")\n    ),\n    \"component\", \"02_jvm_heap_free\", \"\", \"\"\n  )\n\n  or \n\n  label_replace(\n    (\n      label_replace(\n          jvm_memory_used_bytes{area=\"nonheap\"}\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\", \n          \"$1\", \n          \"instance\", \n          \"(.*)\")\n    ),\n    \"component\", \"03_jvm_nonheap_used\", \"\", \"\"\n  )\n\n  or\n\n  label_replace(\n    (\n      label_replace(\n          (jvm_memory_committed_bytes{area=\"nonheap\"} - jvm_memory_used_bytes{area=\"nonheap\"})\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\",\n          \"$1\",\n          \"instance\",\n          \"(.*)\")\n    ),\n    \"component\", \"04_jvm_nonheap_free\", \"\", \"\"\n  )\n\n\n\n  ############################################################\n  # 03 — ROCKSDB BLOCK CACHE\n  ############################################################\n\n  or\n  label_replace(\n    (\n      label_replace(\n        (rocksdb_shared_cache_block_cache_usage{} * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")),\n        \"name\", \n        \"$1\", \n        \"instance\", \n        \"(.*)\")\n    ),\n    \"component\", \"05_rocksdb_block_cache\", \"\", \"\"\n  )\n\n  ############################################################\n  # 04 — ROCKSDB INDEX/FILTER\n  ############################################################\n\n  or\n  label_replace(\n    (\n      label_replace(\n        (kafka_stream_state_estimate_table_readers_mem{} * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")),\n        \"name\", \n        \"$1\", \n        \"instance\", \n        \"(.*)\")\n    ),\n    \"component\", \"06_rocksdb_index_filter\", \"\", \"\"\n  )\n\n\n  ############################################################\n  # 05 — ROCKSDB MEMTABLES\n  ############################################################\n\n\n  or\n  label_replace(\n    (\n      label_replace(\n        (kafka_stream_state_size_all_mem_tables{} * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")),\n        \"name\", \n        \"$1\", \n        \"instance\", \n        \"(.*)\")\n    ),\n    \"component\", \"07_rocksdb_memtables\", \"\", \"\"\n  )\n\n\n  ############################################################\n  # 06 — UNMAPPED PAGE CACHE\n  ############################################################\n\n  or\n\n  label_replace(\n    (\n      container_memory_bytes{key=\"file\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"}\n      - ignoring(key)\n        container_memory_bytes{key=\"file_mapped\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"}\n    ),\n    \"component\", \"08_unmapped_page_cache\", \"\", \"\"\n  )\n\n)",
     "legendFormat": "{{name}}  - {{component}}"
    }
   ]
  },
  {
   "title": "Container & JVM Memory Breakdown - $container",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 35 },
   "repeat": "container",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, component) (\n\n  label_replace(\n    (\n      label_replace(\n          jvm_memory_used_bytes{area=\"heap\"}\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\", \n          \"$1\", \n          \"instance\", \n          \"(.*)\")\n    ),\n    \"component\", \"01_jvm_heap_used\", \"\", \"\"\n  )\n\n  or\n\n  label_replace(\n    (\n      label_replace(\n          (jvm_memory_committed_bytes{area=\"heap\"} - jvm_memory_used_bytes{area=\"heap\"})\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\",\n          \"$1\",\n          \"instance\",\n          \"(.*)\")\n    ),\n    \"component\", \"02_jvm_heap_free\", \"\", \"\"\n  )\n\n  or \n\n  label_replace(\n    (\n      label_replace(\n          jvm_memory_used_bytes{area=\"nonheap\"}\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\", \n          \"$1\", \n          \"instance\", \n          \"(.*)\")\n    ),\n    \"component\", \"03_jvm_nonheap_used\", \"\", \"\"\n  )\n\n  or\n\n  label_replace(\n    (\n      label_replace(\n          (jvm_memory_committed_bytes{area=\"nonheap\"} - jvm_memory_used_bytes{area=\"nonheap\"})\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\",\n          \"$1\",\n          \"instance\",\n          \"(.*)\")\n    ),\n    \"component\", \"04_jvm_nonheap_free\", \"\", \"\"\n  )\n\n\n\n  ############################################################\n  # 03 — ROCKSDB BLOCK CACHE\n  ############################################################\n\n  or\n  label_replace(\n    (\n      label_replace(\n        (rocksdb_shared_cache_block_cache_usage{} * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")),\n        \"name\", \n        \"$1\", \n        \"instance\", \n        \"(.*)\")\n    ),\n    \"component\", \"05_rocksdb_block_cache\", \"\", \"\"\n  )\n\n  ############################################################\n  # 04 — ROCKSDB INDEX/FILTER\n  ############################################################\n\n  or\n  label_replace(\n    (\n      label_replace(\n        (kafka_stream_state_estimate_table_readers_mem{} * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")),\n        \"name\", \n        \"$1\", \n        \"instance\", \n        \"(.*)\")\n    ),\n    \"component\", \"06_rocksdb_index_filter\", \"\", \"\"\n  )\n\n\n  ############################################################\n  # 05 — ROCKSDB MEMTABLES\n  ############################################################\n\n\n  or\n  label_replace(\n    (\n      label_replace(\n        (kafka_stream_state_size_all_mem_tables{} * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\")),\n        \"name\", \n        \"$1\", \n        \"instance\", \n        \"(.*)\")\n    ),\n    \"component\", \"07_rocksdb_memtables\", \"\", \"\"\n  )\n\n\n  ############################################################\n  # 06 — UNMAPPED PAGE CACHE\n  ############################################################\n\n  or\n\n  label_replace(\n    (\n      container_memory_bytes{key=\"file\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"}\n      - ignoring(key)\n        container_memory_bytes{key=\"file_mapped\", id=~\"^[a-f0-9]{64}$\", service=~\"$service\", name=~\"$container\"}\n    ),\n    \"component\", \"08_unmapped_page_cache\", \"\", \"\"\n  )\n\n  or \n\n  label_replace(\n    (\n      label_replace(\n          (java_lang_threading_threadcount{} * 1048576)\n             * on (instance) group_left(name) label_replace(container_info{service=~\"$service\", name=~\"$container\"}, \"instance\", \"$1\", \"name\", \"(.*)\"),\n          \"name\", \n          \"$1\", \n          \"instance\", \n          \"(.*)\")\n    ),\n    \"component\", \"13_jvm_thread_est\", \"\", \"\"\n  )\n\n)",
     "legendFormat": "{{name}}  - {{component}}"
    }
   ]
  }
 ]
}