
bootstrap.servers=localhost:9092
security.protocol=SASL_PLAINTEXT
sasl.mechanism=OAUTHBEARER

sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.token.endpoint.url="http://localhost:8080/realms/kafka/protocol/openid-connect/token" oauth.client.id="app-ui" oauth.client.secret="app-ui-secret" oauth.scope="openid kafka" ;


# Client callback handler
sasl.login.callback.handler.class=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
