networks:
  default:
    external: true
    name: ksd

services:
#  keycloak:
#    image: quay.io/keycloak/keycloak:25.0.0
#    container_name: ksd-keycloak
#    hostname: keycloak
#    environment:
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HTTP_ENABLED: 'true'
#      KC_HOSTNAME_STRICT: 'false'
#      KC_HTTP_RELATIVE_PATH: '/auth'
#    ports:
#      - "8080:8080"
#    command:
#      - start-dev
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/admin/realms"]
#      interval: 15s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
  keycloak:
    image: keycloak/keycloak:24.0.4
    container_name: ksd-keycloak
    hostname: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_HTTP_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
    ports:
      - "8080:8080"
    command:
      - start-dev
    healthcheck:
      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/8080"]
      start_period: 8s
      interval: 4s
      timeout: 5s
      retries: 4
#  keycloak:
#    container_name: ksd-keycloak
#    hostname: keycloak
#    image: keycloak/keycloak:24.0.4
#    healthcheck:
#      test: cat /proc/1/status | grep State
#      start_period: 10s
#      interval: 5s
#      timeout: 5s
#      retries: 3
#    command: [ "start-dev", "--import-realm", "--https-key-store-password=broker_secret", "--https-key-store-file=/keycloak.keystore.jks" ]
#    environment:
#      DB_VENDOR: MYSQL
#      DB_ADDR: mysql
#      DB_DATABASE: keycloak
#      DB_USER: keycloak
#      DB_PASSWORD: keycloak
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: keycloak
#    ports:
#      - "8080:8080"
#      - "8443:8443"
#    volumes:
#      - ./keycloak.keystore.jks:/keycloak.keystore.jks
#      - ./realms/:/opt/keycloak/data/import/

  kafka-broker:
    image: apache/kafka:4.1.1
    container_name: ksd-kafka-broker
    hostname: kafka-broker
#    depends_on:
#      keycloak:
#        condition: service_healthy
    environment:
      # Cluster setup
      CLUSTER_ID: MkQzNzQ1NTk2OTJmNDAxZA
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 9223372036854775807
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      # Kraft controller setup
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER

      # Listeners
      KAFKA_LISTENERS: EXTERNAL_SASL://0.0.0.0:9092,BROKER://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL_SASL://localhost:9092,BROKER://kafka-broker:9093,CONTROLLER://kafka-broker:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL_SASL:SASL_PLAINTEXT,BROKER:PLAINTEXT,CONTROLLER:PLAINTEXT

      # SASL/OAuth configuration
      KAFKA_SASL_ENABLED_MECHANISMS: OAUTHBEARER
      KAFKA_LISTENER_NAME_EXTERNAL__SASL_SASL_ENABLED_MECHANISMS: OAUTHBEARER


      KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler
      KAFKA_LISTENER_NAME_EXTERNAL__SASL_SASL_OAUTHBEARER_JWT_VALIDATOR_CLASS: org.apache.kafka.common.security.oauthbearer.BrokerJwtValidator
      KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: http://keycloak:8080/realms/master/protocol/openid-connect/certs

      KAFKA_LISTENER_NAME_EXTERNAL__SASL_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka
      KAFKA_LISTENER_NAME_EXTERNAL__SASL_SASL_OAUTHBEARER_EXPECTED_ISSUER: http://localhost:8080/realms/master

      # THIS IS NEEDED !!!! AND NOT WITH LISTERNNAE
      #KAFKA_SASL_OAUTHBEARER_JWT_VALIDATOR_CLASS: org.apache.kafka.common.security.oauthbearer.BrokerJwtValidator

      #KAFKA_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka

      #KAFKA_SASL_OAUTHBEARER_EXPECTED_ISSUER: http://localhost:8080/realms/master

      KAFKA_SASL_OAUTHBEARER_PRINCIPAL_CLAIM_NAME: "client_id"


# these are all failed attempts
      #KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_JWT_VALIDATOR_CLASS: xxxx_org.apache.kafka.common.security.oauthbearer.BrokerJwtValidator
      #KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: http://keycloak:8080/realms/master/protocol/openid-connect/certs_LLLLLLLLLL
      #KAFKA_LISTENER_NAME_EXTERNAL_SASL_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka_really
      #KAFKA_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka_yyy
      #KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_EXPECTED_AUDIENCE: kafka_zzz

  #BrokerJwtValidator
#    listener.name.external.oauthbearer.sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required ssl.truststore.location="/usr/lib/jvm/jre-17-openjdk/lib/security/cacerts" ssl.truststore.password="changeit" unsecuredLoginStringClaim_sub="commsbroker";
#    listener.name.external.sasl.oauthbearer.jwks.endpoint.url: https://sso-cbc2.cce.af.mil/auth/realms/CBC2/protocol/openid-connect/certs
#    listener.name.external.sasl.oauthbearer.expected.audience: cbc2
#    listener.name.external.sasl.oauthbearer.sub.claim.name: clientId
#    listener.name.external.oauthbearer.sasl.server.callback.handler.class: org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler

#    listener.name.external.sasl.oauthbearer.jwks.endpoint.url: https://sso-cbc2.cce.af.mil/auth/realms/CBC2/protocol/openid-connect/certs
#    listener.name.external.sasl.oauthbearer.expected.audience: cbc2
#    listener.name.external.sasl.oauthbearer.sub.claim.name: clientId
#    listener.name.external.oauthbearer.sasl.server.callback.handler.class: org.apache.kafka.common.security.oauthbearer.secured.OAuthBearerValidatorCallbackHandler

      #BrokerJwtValidator
#sasl.oauthbearer.jwks.endpoint.url

      #KAFKA_SASL_OAUTHBEARER_SCOPE_CLAIM: scope
      #KAFKA_SASL_OAUTHBEARER_EXPECTED_AUDIENCE: "cbc2"  # or whatever audience Keycloak issues
      #KAFKA_SASL_OAUTHBEARER_EXPECTED_ISSUER: "http://localhost:8080/realms/master"

#      KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_SUB_CLAIM_NAME: clientId
      #KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_SUB_CLAIM_NAME: client_id

#        -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5005

      # JVM options for JAAS and allowed URLs
#      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf -Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=http://keycloak:8080/realms/kafka/protocol/openid-connect/certs,http://keycloak:8080/realms/kafka/protocol/openid-connect/token
      KAFKA_OPTS: >
        -Dlog4j.rootLogger=DEBUG,STDOUT
        -Dlog4j.logger.org.apache=DEBUG
        -Dlog4j.logger.org.apache.kafka.common.security=DEBUG
        -Dlog4j.logger.org.apache.kafka.common.security.oauthbearer=DEBUG
        -Dlog4j.logger.org.apache.kafka.common.security.authenticator=DEBUG
        -Dlog4j.logger.org.apache.kafka=INFO
        -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf 
        -Dorg.apache.kafka.sasl.oauthbearer.allowed.urls=http://keycloak:8080/realms/master/protocol/openid-connect/certs,http://keycloak:8080/realms/master/protocol/openid-connect/token,http://localhost:8080/realms/master/protocol/openid-connect/certs,http://localhost:8080/realms/master/protocol/openid-connect/token

      #KAFKA_SASL_OAUTHBEARER_JWKS_ENDPOINT_URL: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
      #KAFKA_LISTENER_NAME_EXTERNAL__SASL_OAUTHBEARER_SASL_SERVER_CALLBACK_HANDLER_CLASS: "org.apache.kafka.common.security.oauthbearer.OAuthBearerValidatorCallbackHandler"

    ports:
      - "9092:9092"
      - "5005:5005"
    volumes:
      - ./secrets/broker_jaas.conf:/etc/kafka/secrets/broker_jaas.conf:ro
#    healthcheck:
#      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#      start_period: 30s
#    healthcheck:
#      test: ["CMD-SHELL", "echo > /dev/tcp/127.0.0.1/9092"]
#      start_period: 5s
#      interval: 5s
#      timeout: 5s
#      retries: 3

#  kafka-ui:
#    image: provectuslabs/kafka-ui:latest
#    container_name: ksd-kafka-ui
#    environment:
#      KAFKA_CLUSTERS_0_NAME: oauth-cluster
#      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-broker:9092
#      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: OAUTHBEARER
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required ;"
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_LOGIN_CALLBACK_HANDLER_CLASS: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginCallbackHandler
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_OAUTHBEARER_TOKEN_ENDPOINT_URL: http://keycloak:8080/realms/master/protocol/openid-connect/token
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_OAUTHBEARER_JWT_RETRIEVER_CLASS: org.apache.kafka.common.security.oauthbearer.DefaultJwtRetriever
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_OAUTHBEARER_CLIENT_CREDENTIALS_CLIENT_ID: kafka-ui
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_OAUTHBEARER_CLIENT_CREDENTIALS_CLIENT_SECRET: kafka-ui-secret
#      KAFKA_CLUSTERS_0_PROPERTIES_SASL_OAUTHBEARER_SCOPE: openid kafka
#    ports:
#      - "8081:8080"
#    depends_on:
#      - kafka-broker
